const products=[
{id:1,name:'Samsung Galaxy A16 4G LTE (128GB + 4GB)',cat:'electronics',price:44109.82,old:0,image:'https://a.allegroimg.com/original/11d93c/e31829304afd850a5ca50a77299a/SAMSUNG-A16-LTE-4GB-128GB-DS-NFC-5000mAh-6-7-2340x1080-AMOLED-90Hz-50Mpx',rating:'★★★★☆',badge:'AMAZON PICK',affiliateUrl:'https://www.amazon.com/Samsung-International-SM-A165F-Factory-Unlocked/dp/B0DM1S54MZ?crid=32OVVOJ8IH4QH&dib=eyJ2IjoiMSJ9.mNK68gb2mdCbf0_bZtfIGbLzE10-quRi22-a74KslQ3hYX1Uvn9QNpvViPz4HvGA1rQcGz5CIJNOd6PxYME5sxCVvI4y0sr7RoGfCSRQohjTYxbdbocPllGI-Eo0jgq69Ubk2kab08pcqYAXSQx6PuFcZpOC38ys2T4dgLA0UUb8ZkShoDB_oOTSSfoGCRGCDPhgd5y_3jvM0a-B_Gq8YL--A6AD0j-4Rdl6N_44lkA.UR77OaUXGeHDzjxVgUCQJCSoZJ1i103rhMmhtF5XOG4&dib_tag=se&keywords=android%2Bphone&qid=1787202024&sprefix=and%2Caps%2C786&sr=8-1&th=1&linkCode=ll2&tag=mrkstore03-20&linkId=7f11c5ca1932ee90497da1c459bfcb4e&language=en_US&gaOptInStatus=true&ref_=as_li_ss_tl'},
{id:2,name:'Kensington SD5910T DisplayLink Docking Station Thunderbolt 4 — Quad 4K, 100W PD, 16-in-1',cat:'electronics',price:80201.95,old:0,image:'https://m.media-amazon.com/images/I/81dvI8+kecL._AC_SL1500_.jpg',rating:'★★★★☆',badge:'AMAZON PICK',affiliateUrl:'https://www.amazon.com/Kensington-DisplayLink-Thunderbolt-Chipsets-K35233NA/dp/B0DLP38RZM?crid=1F3HINH3V2QXH&dib=eyJ2IjoiMSJ9.H7DG6lSpEx0tcfukifJhZ6v9vcNwZFdHwchn4PB8gA8a9OPfu7cUCVRORexwih1b6gRGoVZ2cdxG0mcokRaIGB_aU9VSSDLEABsbtrzPu6OnzITnCWwiWyEp0b0yiLM7BsiT2LprkzsC6aYDvH7kExhqz0ZhUuLu21OYAYf6OHodUwZdsd8gOBj7G9iTcl9Wv7hGl9uFU1V2_KsJ7nfgRq989jjCr35urtn-AFMSiXw.qkv0lOW21bIg-xf_Vef2n_2PmKX-mqpqNVSBBTlZ0po&dib_tag=se&keywords=laptop&qid=1787203063&sprefix=laptop%2Caps%2C575&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&linkCode=ll2&tag=mrkstore03-20&linkId=57dc92092299e739a53d1f8c450f7c68&language=en_US&gaOptInStatus=true&ref_=as_li_ss_tl',asin:'B0DLP38RZM',model:'K35233NA',details:'Thunderbolt 4 · Quad 4K @ 60Hz · 100W PD / 96W certified · 2× HDMI 2.0 / DisplayPort 1.4 · 2× downstream Thunderbolt 4 · USB-C / USB-A · SD + MicroSD · 2.5Gbps Ethernet',ratingsCount:15},
{id:3,name:'Smart Watch Series X',cat:'electronics',price:5999,old:7999,icon:'⌚',rating:'★★★★☆',badge:'DEAL',affiliateUrl:''},
{id:4,name:'Premium Everyday Sneakers',cat:'fashion',price:4299,old:5999,icon:'👟',rating:'★★★★★',badge:'POPULAR',affiliateUrl:''},
{id:5,name:'Minimal Travel Backpack',cat:'fashion',price:3299,old:4499,icon:'🎒',rating:'★★★★☆',badge:'',affiliateUrl:''},
{id:6,name:'Modern Desk Lamp',cat:'home',price:2499,old:3499,icon:'💡',rating:'★★★★★',badge:'DEAL',affiliateUrl:''},
{id:7,name:'Ceramic Coffee Set',cat:'home',price:1899,old:2599,icon:'☕',rating:'★★★★☆',badge:'',affiliateUrl:''},
{id:8,name:'Wireless Bluetooth Speaker',cat:'electronics',price:3799,old:4999,icon:'🔊',rating:'★★★★★',badge:'NEW',affiliateUrl:''},
{id:9,name:'Everyday Care Kit',cat:'beauty',price:2199,old:2999,icon:'✨',rating:'★★★★☆',badge:'',affiliateUrl:''}
];
let cart=JSON.parse(localStorage.getItem('mrkCart')||'[]');let activeFilter='all',search='';
const grid=document.getElementById('productGrid'),empty=document.getElementById('emptyState');
const money=n=>n?('Rs. '+n.toLocaleString('en-PK',{maximumFractionDigits:0})):'';
function renderProducts(){const items=products.filter(p=>(activeFilter==='all'||p.cat===activeFilter)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())));grid.innerHTML=items.map(p=>`<article class="product"><div class="product-img">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:p.icon}</div>${p.badge?`<span class="badge">${p.badge}</span>`:''}<div class="product-body"><div class="rating">${p.rating}${p.ratingsCount?` <small>(${p.ratingsCount})</small>`:''}</div><h3>${p.name}</h3>${p.price?`<div><span class="price">${money(p.price)}</span>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div>`:`<div class="price">See price on Amazon</div>`}${p.model?`<div class="product-meta">Model: ${p.model} · ASIN: ${p.asin}</div>`:''}${p.details?`<p class="product-details">${p.details}</p>`:''}<div class="product-actions"><button class="add" data-add="${p.id}">Add to cart</button>${p.affiliateUrl?`<a class="buy-amazon" href="${p.affiliateUrl}" target="_blank" rel="sponsored noopener noreferrer" data-affiliate="${p.id}">View on Amazon ↗</a>`:`<button class="buy-amazon disabled" type="button" title="Affiliate link not configured">Affiliate link pending</button>`}</div></div></article>`).join('');empty.hidden=items.length>0;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(+b.dataset.add));document.querySelectorAll('[data-affiliate]').forEach(a=>a.onclick=()=>trackAffiliate(+a.dataset.affiliate));}
function save(){localStorage.setItem('mrkCart',JSON.stringify(cart));renderCart();}
function addToCart(id){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();toast(p.name+' added to cart');}
function changeQty(id,delta){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);save();}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('cartCount').textContent=count;const wrap=document.getElementById('cartItems');if(!cart.length){wrap.innerHTML='<div class="empty">Your cart is empty.<br><small>Add something you love.</small></div>';}else wrap.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="cart-item"><div class="mini">${p.image?`<img src="${p.image}" alt="${p.name}">`:p.icon}</div><div><strong>${p.name}</strong><small>${p.price?money(p.price)+' each':'See price on Amazon'}</small><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button></div></div><strong>${p.price?money(p.price*x.qty):'Amazon'}</strong></div>`}).join('');const total=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id).price||0)*x.qty,0);document.getElementById('cartTotal').textContent=money(total);wrap.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1));wrap.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1));}
function openCart(){document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('show');document.getElementById('cartDrawer').setAttribute('aria-hidden','false')}
function closeCart(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('overlay').classList.remove('show');document.getElementById('cartDrawer').setAttribute('aria-hidden','true')}
function trackAffiliate(id){const p=products.find(x=>x.id===id);if(!p?.affiliateUrl)return;const key='mrkAffiliateClicks';const data=JSON.parse(localStorage.getItem(key)||'{}');data[id]=(data[id]||0)+1;localStorage.setItem(key,JSON.stringify(data));}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProducts()});
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));document.getElementById('products').scrollIntoView({behavior:'smooth'});renderProducts()});
document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();search=document.getElementById('searchInput').value.trim();activeFilter=document.getElementById('categorySelect').value;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'})};
document.getElementById('categorySelect').onchange=e=>{activeFilter=e.target.value;renderProducts()};
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;
document.getElementById('checkoutBtn').onclick=()=>{if(!cart.length)return toast('Your cart is empty');toast('For affiliate products, use the Amazon button on the product page.')};
document.getElementById('accountBtn').onclick=()=>toast('Customer account module will be connected to the backend.')
document.getElementById('menuBtn').onclick=()=>document.getElementById('categories').scrollIntoView({behavior:'smooth'});
document.getElementById('newsletterForm').onsubmit=e=>{e.preventDefault();toast('Thanks! You are subscribed to MRK Insider.');e.target.reset()};
renderProducts();renderCart();
